# Generated by Django 3.2.10 on 2023-10-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='foto_de_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img/perfil/'),
        ),
    ]
