# Generated by Django 3.2.10 on 2023-10-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_userinfo_foto_de_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='foto_de_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='apps/assets/img/perfil/'),
        ),
    ]
