# Generated by Django 3.2.10 on 2023-09-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='numero',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
