# Generated by Django 3.2.10 on 2023-10-31 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_alter_userinfo_foto_de_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividades', models.CharField(max_length=500, null=True)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionHat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contratacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreAspirante', models.CharField(max_length=200)),
                ('uploadedNotes', models.FileField(upload_to='Notas/')),
                ('uploadedCV', models.FileField(upload_to='CV/')),
                ('is_contratado', models.BooleanField(default=False, null=True)),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
                ('comentarios', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Documentos contratacion',
                'ordering': ['-dateTimeOfUpload'],
            },
        ),
        migrations.CreateModel(
            name='CredentialToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploadedFile', models.FileField(upload_to='Archivos Psicologicos/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Documentos Psicologicos',
                'ordering': ['-dateTimeOfUpload'],
            },
        ),
        migrations.CreateModel(
            name='documentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoDocumento', models.CharField(max_length=200)),
                ('uploadedFile', models.FileField(upload_to='Documentos Personales/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentfiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Documentos Personales',
                'ordering': ['-dateTimeOfUpload'],
            },
        ),
        migrations.CreateModel(
            name='Documentoslegales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploadedFile', models.FileField(upload_to='Archivos Legales/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legalfiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Documentos Legales',
                'ordering': ['-dateTimeOfUpload'],
            },
        ),
        migrations.CreateModel(
            name='Documentosmedicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploadedFile', models.FileField(upload_to='Archivos Medicos/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicfiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Documentos Medicos',
                'ordering': ['-dateTimeOfUpload'],
            },
        ),
        migrations.CreateModel(
            name='Egresos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.CharField(max_length=250, null=True)),
                ('egreso', models.CharField(max_length=250, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Salida empresa',
            },
        ),
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_hat', models.CharField(max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Justificantesmedicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploadedFile', models.FileField(upload_to='Justificantes Medicos/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='justifyfiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Justificantes Medicos',
                'ordering': ['-dateTimeOfUpload'],
            },
        ),
        migrations.CreateModel(
            name='Kaisen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploadedFile', models.FileField(upload_to='Actas Kaisen/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'kaizen',
                'ordering': ['-dateTimeOfUpload'],
            },
        ),
        migrations.CreateModel(
            name='TimestampedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
            ],
        ),
        migrations.RemoveField(
            model_name='asignacionpuesto',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='asignacionpuesto',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='asignacionpuesto',
            name='puesto',
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='AsignacionPuesto',
        ),
        migrations.DeleteModel(
            name='Puesto',
        ),
        migrations.AddField(
            model_name='asignacionhat',
            name='hat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hats', to='home.hat'),
        ),
        migrations.AddField(
            model_name='asignacionhat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividades',
            name='hat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='home.hat'),
        ),
    ]
